<a href="https://colab.research.google.com/github/Taweechokk/INC492/blob/main/INC492_690_Week02_01_NumPy_Arrays_StudentVersion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **INC492/690: Introduction to Data Science**

Week02 - Python for Data Science
-----------------------------------
Dr. Teema Leangarun

Department of Controls System and Instrumentation Engineering

Facullty of Engineering, KMUTT


# NumPy

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries.

We will only learn the basics of NumPy.

## Using NumPy

Import it as a library:

In [1]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.



# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.



## 1.1) Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [4]:
arr1 =np.array([1,2,3])

In [5]:
arr1

array([1, 2, 3])

In [9]:
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [10]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## 1.2) Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate arrays of zeros or ones

In [15]:
np.zeros(3)

array([0., 0., 0.])

In [16]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np.zeros(3)+1

array([1., 1., 1.])

In [18]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
“ linspace ” refers to generating linearly spaced values.

Return evenly spaced numbers over a specified interval.


In [19]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [20]:
np.linspace(0,10,40)

array([ 0.        ,  0.25641026,  0.51282051,  0.76923077,  1.02564103,
        1.28205128,  1.53846154,  1.79487179,  2.05128205,  2.30769231,
        2.56410256,  2.82051282,  3.07692308,  3.33333333,  3.58974359,
        3.84615385,  4.1025641 ,  4.35897436,  4.61538462,  4.87179487,
        5.12820513,  5.38461538,  5.64102564,  5.8974359 ,  6.15384615,
        6.41025641,  6.66666667,  6.92307692,  7.17948718,  7.43589744,
        7.69230769,  7.94871795,  8.20512821,  8.46153846,  8.71794872,
        8.97435897,  9.23076923,  9.48717949,  9.74358974, 10.        ])

### eye

Creates an identity matrix

In [21]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## 1.3) Random

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [22]:
np.random.rand(2)

array([0.64828476, 0.65072547])

In [23]:
np.random.rand(5,5)

array([[0.64276414, 0.66859718, 0.56921854, 0.92144366, 0.49037571],
       [0.18661354, 0.4668503 , 0.05872059, 0.36612718, 0.59195297],
       [0.76627524, 0.79708948, 0.00585285, 0.5185873 , 0.05102358],
       [0.24877443, 0.15256349, 0.20126152, 0.21950449, 0.34726046],
       [0.66861322, 0.82183466, 0.29853812, 0.83352823, 0.7868902 ]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [24]:
np.random.randn(10)

array([ 1.46506723,  0.54785427, -0.19470694,  2.41267417,  0.76697583,
        0.1887387 ,  0.78859312, -1.96839777, -0.27363649, -1.25526162])

In [25]:
np.random.rand(5,5)

array([[0.50544704, 0.24086218, 0.6300201 , 0.51765117, 0.55427486],
       [0.93088587, 0.0375137 , 0.96526437, 0.46389224, 0.1429371 ],
       [0.70735025, 0.10934997, 0.63835253, 0.67340493, 0.94566429],
       [0.04071449, 0.5246189 , 0.42081921, 0.93366808, 0.97270435],
       [0.85683943, 0.71439623, 0.5351351 , 0.85377524, 0.35700382]])

## 1.4) Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [26]:
arr = np.arange(25)
rand_arr =np.random.randint(0,50,10)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
rand_arr

array([46, 44, 46, 41,  6, 26,  5, 15, 34, 31])

## 1.5) Reshape
Returns an array containing the same data with a new shape.

In [28]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

## 1.6) max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [30]:
rand_arr

array([46, 44, 46, 41,  6, 26,  5, 15, 34, 31])

In [31]:
rand_arr.max()

46

In [32]:
# argmax() function returns indices of the max element of the array in a particular axis.
rand_arr.argmax()


0

In [33]:
rand_arr.min()

5

In [34]:
rand_arr.argmin()

6

## 1.7) Shape

Shape is an attribute that arrays have (not a method):

In [35]:
# Vector
arr.shape

(25,)

In [36]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [37]:
arr.reshape(1,25).shape

(1, 25)

In [38]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [39]:
arr.reshape(25,1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array:

In [40]:
arr.dtype

dtype('int64')

# Great Job!